title: My Daily logs
author: 0-R1
# email: i no have mail
description: > # this means to ignore newlines until "twitter_username:"
 Best way to understand somthing is trying 
 to teach it. & i'm not doing that here so
 no thank you

# social links
github_username:  0-R1
rss: rss


show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
